### ISSUE TITLE
Running Consumers as Workers

### ISSUE THREAD

**Issue by jordanvector** [magento/magento-cloud#481]
I have searched high and low across the internet and I have not found a single actual example of how to use workers in magento cloud.

The only example I can find is [this](https://devdocs.magento.com/cloud/project/project-conf-files_magento-app.html?itm_source=devdocs&itm_medium=quick_search&itm_campaign=federated_search&itm_term=worke#workers). Which is not an actual example.

 Platform.sh (same vendor as magento cloud) has a specific example [here](https://github.com/platformsh-templates/magento2ce/blob/master/.platform.app.yaml#L100).

Consumers specifically are a good candidate for workers because they are always supposed to be listening for messages, and processing as they come in. What would be great is if we can create a single worker to run all consumer processes.

So far I have something like this I am testing

```
workers:
    queue:
        size: S
        disk: 128
        commands:
            start: |
                bin/magento  queue:consumers:list | xargs -n1 bin/magento queue:consumers:start --single-thread --max-messages=1000
```

Essentially this script list all the consumers and then runs each as a single thread.  Is a worker like this to list and run all consumers feasible? If so is there a better way than the command I have above?
